# Generated by Django 5.1.3 on 2025-02-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SL', 'Sustainable Living'), ('RU', 'Recycled & Upcycled'), ('ON', 'Organic & Natural'), ('HE', 'Handmade & Ethical'), ('BW', 'Bamboo & Wooden'), ('SF', 'Sustainable Fashion'), ('EKB', 'Eco-Friendly Kids & Babies')], default='SL', max_length=20, verbose_name='Category'),
        ),
    ]
