# Generated by Django 5.1.3 on 2025-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Personal Care'), ('FA', 'Fashion'), ('OF', 'Organic Food'), ('KD', 'Kitchen and Decor'), ('EL', 'Electronics'), ('EKB', 'Eco-Friendly Kids & Babies')], default='PC', max_length=20, verbose_name='Category'),
        ),
    ]
